// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYA9f1x4cC_pmx0Nb31Tz6qBFJPv2VLqw',
    appId: '1:46719551575:android:cc87e0163c9ae0ba0e3b12',
    messagingSenderId: '46719551575',
    projectId: 'break-free-cfebd',
    storageBucket: 'break-free-cfebd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQA7NeButQD2ITQhmSuMq5cikiyl3nDEs',
    appId: '1:46719551575:ios:14d2d267262c24460e3b12',
    messagingSenderId: '46719551575',
    projectId: 'break-free-cfebd',
    storageBucket: 'break-free-cfebd.firebasestorage.app',
    androidClientId: '46719551575-32cc9olk0ps97na39usdibk9ijmhf7rv.apps.googleusercontent.com',
    iosClientId: '46719551575-lnupfn4d04g1ai346e7anpg619aaqpd2.apps.googleusercontent.com',
    iosBundleId: 'app.breakfree.mobile',
  );
}
