// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHBsvNUL8x3XgILXaVkgzyIwPVwNiQlGE',
    appId: '1:41932458800:android:c3c066cdd90cabb2a856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_D7t3WR3tKDPF1aBlGJdkcVHj1tbjEbU',
    appId: '1:41932458800:ios:0e21b87b2a45e57aa856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
    androidClientId: '41932458800-pclmhh9s79ktp0iqa804au6pkk8akvd1.apps.googleusercontent.com',
    iosClientId: '41932458800-qve8e6ir9eu5aul9kmt5j00kf3pao4l1.apps.googleusercontent.com',
    iosBundleId: 'app.breakfree.mobile',
  );
}
